window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t456_setListMagin(recid,imglogo){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menu=rec.querySelector('.t456');var leftSide=menu?menu.querySelector('.t456__leftwrapper'):null;var list=menu?menu.querySelector('.t456__list'):null;var leftSideWidth=leftSide?leftSide.offsetWidth:0;if(list)list.style.marginRight=(imglogo?leftSideWidth:leftSideWidth+30)+'px'}
function t280_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var isChrome=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor);var isAndroid=/(android)/i.test(navigator.userAgent);var menu=rec.querySelector('.t280');var menuItems=rec.querySelectorAll('.t280__menu__item');var menuLinks=rec.querySelectorAll('.t978__menu-link');var menuContainer=rec.querySelector('.t280__menu');var menuBurger=menu?menu.querySelector('.t-menuburger'):null;var clickElementsList=rec.querySelectorAll('.t280 .t-menuburger, .t280__menu__bg, .t280__menu__link:not(.tooltipstered):not(.t280__menu__link_submenu), .t978__tooltip-menu_mobile');Array.prototype.forEach.call(clickElementsList,function(clickElement){clickElement.addEventListener('click',function(){if(clickElement.closest('.t280__menu__link.tooltipstered')||clickElement.closest('.t794__tm-link'))
return;if(isChrome&&isAndroid&&menuItems.length>10&&window.location.hash){setTimeout(function(){var hash=window.location.hash;window.location.hash='';window.location.hash=hash},50)}
if(!clickElement.closest('.t978__tm-link, .t966__tm-link')){document.body.classList.toggle('t280_opened');if(menu)menu.classList.toggle('t280__main_opened')}
if(clickElement.classList.contains('t-menuburger')){var expandedStatus=clickElement.classList.contains('t-menuburger-opened');clickElement.setAttribute('aria-expanded',expandedStatus)}
t280_changeSize(recid);t280_highlight(recid)})});document.addEventListener('click',function(e){if(e.target.closest('.t978__tm-link, .t966__tm-link, .t-menusub__target-link, .t978__menu-link_hook, .t978__menu-item')){setTimeout(function(){t280_changeSize(recid);if(menuContainer)menuContainer.style.transition='none'},200)}});Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t280_changeSize(recid)})});if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){document.body.classList.remove('t280_opened');menu.classList.remove('t280__main_opened')})}
var submenuLinks=rec.querySelectorAll('.t-menusub__link-item');Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){document.body.classList.remove('t280_opened');if(menu)menu.classList.remove('t280__main_opened');if(menuBurger){menuBurger.classList.remove('t-menuburger-opened');menuBurger.setAttribute('aria-expanded',!1)}})});if(submenuLinks.length>0){document.addEventListener('submenuShow',function(){t280_changeSize(recid)})}}
function t280_changeSize(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t280__menu');var menuBottom=rec.querySelector('.t280__bottom');var menuContainer=rec.querySelector('.t280__container');var menuWrapper=rec.querySelector('.t280__menu__wrapper');var menuHeight=menu?menu.offsetHeight:0;var menuBottomHeight=menuBottom?menuBottom.offsetHeight:0;var menuContainerHeight=menuContainer?menuContainer.offsetHeight:0;var padding=140;if(menuHeight>document.documentElement.clientHeight-(menuBottomHeight+menuContainerHeight+padding)){if(menuWrapper)menuWrapper.classList.add('t280__menu_static');if(menu)menu.style.paddingTop=(menuContainerHeight||0)+'px'}else{if(menuWrapper)menuWrapper.classList.remove('t280__menu_static');if(menu)menu.style.paddingTop=''}}
function t280_changeBgOpacityMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlocks=rec.querySelectorAll('.t280__container__bg');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity2');var menuShadowOpacity=parseInt(menu.getAttribute('data-menushadow'),10)||0;menuShadowOpacity/=100;var menuShadowCSS=menu.getAttribute('data-menushadow-css');menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if((window.pageYOffset>20&&bgOpacityTwo==='0')||(window.pageYOffset<=20&&(bgOpacity==='0.0'||bgOpacity==='0'))||(!menuShadowOpacity&&!menuShadowCSS)){menu.style.boxShadow='none'}else if(menuShadowCSS){menu.style.boxShadow=menuShadowCSS}else if(menuShadowOpacity){menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowOpacity+')'}})}
function t280_appearMenu(){var menuBlocks=document.querySelectorAll('.t280');Array.prototype.forEach.call(menuBlocks,function(menuBlock){var menu=menuBlock.querySelector('.t280__positionfixed');if(menu){var appearOffset=menuBlock.getAttribute('data-appearoffset');if(appearOffset&&appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor(window.innerHeight*(parseInt(appearOffset)/100))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(isNaN(appearOffset))return;if(window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t280_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t280_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t280_slideUpElement(menu,menuHeight,direction){var diff=direction==='toTop'?0:menuHeight;var diffOpacity=direction==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=direction==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=direction==='toTop'?diff+menuHeight/20:diff-menuHeight/20;if(direction==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(direction==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t280_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll(".t280__menu a[href='"+url+"'], "+".t280__menu a[href='"+url+"/'], "+".t280__menu a[href='"+pathname+"'], "+".t280__menu a[href='/"+pathname+"'], "+".t280__menu a[href='"+pathname+"/'], "+".t280__menu a[href='/"+pathname+"/']"+(hash?", .t280__menu a[href='"+hash+"']":'')+(hash?", .t280__menu a[href='/"+hash+"']":'')+(hash?", .t280__menu a[href='"+hash+"/']":'')+(hash?", .t280__menu a[href='/"+hash+"/']":''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t280__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t650_init(recId){t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)})}
function t650_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var wrapper=rec.querySelector('.t650');if(!wrapper)return;var container=rec.querySelector('.t650__container');if(!container)return;var columnsInRow=Number(container.getAttribute('data-columns-in-row'));if(columnsInRow===0||columnsInRow===''){columnsInRow=1}
var allCols=Array.prototype.slice.call(rec.querySelectorAll('.t-card__col'));var rowsArray=[];for(var i=0;i<allCols.length;i+=columnsInRow){rowsArray.push(allCols.slice(i,i+columnsInRow))}
if(window.innerWidth>=960){for(var i=0;i<rowsArray.length;i++){var row=rowsArray[i];var maxHeight=0;var innerCols=[];for(var j=0;j<row.length;j++){innerCols.push(row[j].querySelector('.t650__inner-col'))}
for(var j=0;j<innerCols.length;j++){var col=innerCols[j];var colText=col.querySelector('.t650__text');var colBtn=col.querySelector('.t650__btn-container');var colHeight=colText.offsetHeight+(colBtn?colBtn.offsetHeight:0);if(colHeight>maxHeight)maxHeight=colHeight}
for(var j=0;j<innerCols.length;j++){innerCols[j].style.height=maxHeight+'px'}}}else{var cols=rec.querySelectorAll('.t650__inner-col');for(var i=0;i<cols.length;i++){cols[i].style.height='auto'}}}
function t849_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var togglers=rec.querySelectorAll('.t849__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var accordion=rec.querySelector('.t849__accordion');if(accordion){accordion=accordion.getAttribute('data-accordion')}else{accordion='false'}
var cachedHeight=0;var cachedTop=0;Array.prototype.forEach.call(togglers,function(toggler){toggler.addEventListener('click',function(){var target=toggler;var content=target.nextElementSibling;var triggerButton=target.querySelector('.t849__trigger-button');if(accordion==='true'){Array.prototype.forEach.call(togglers,function(header){if(target!==header){header.classList.remove('t849__opened');t849_slideUp(header.nextElementSibling,target)}})}
if(triggerButton){var isExpanded=triggerButton.getAttribute('aria-expanded')==='true';triggerButton.setAttribute('aria-expanded',!isExpanded);content.hidden=isExpanded}
target.classList.toggle('t849__opened');target.style.pointerEvents='none';t849_slideToggle(target.nextElementSibling,target);if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})});function t849_slideToggle(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=300;if(window.getComputedStyle(target).display==='none'){return t849_slideDown(target,triggerElement,duration)}else{cachedHeight=0;return t849_slideUp(target,triggerElement,duration)}}
function t849_slideUp(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=300;target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.boxSizing='border-box';target.style.height=target.offsetHeight+'px';target.offsetHeight;target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';setTimeout(function(){triggerElement.style.pointerEvents='auto';target.style.display='none';target.style.height='';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty=''},duration)}
function t849_slideDown(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=300;target.style.display='';var cashedDisplay=window.getComputedStyle(target).display;if(cashedDisplay==='none')cashedDisplay='block';target.style.display=cashedDisplay;var targetHeight=target.offsetHeight;var targetTop=target.offsetTop;if(window.visualViewport){var visibleTop=targetTop-window.visualViewport.pageTop;if(cachedTop&&accordion==='true'&&targetTop>cachedTop&&window.scrollY>cachedTop){window.scrollTo(window.scrollX,targetTop-cachedHeight-visibleTop)}}
target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';target.offsetHeight;target.style.boxSizing='border-box';target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.height=targetHeight+'px';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';setTimeout(function(){triggerElement.style.pointerEvents='auto';target.style.height='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty='';cachedHeight=targetHeight;cachedTop=targetTop},duration)}}
function t604_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;t604_imageHeight(rec);t604_arrowWidth(rec);t604_show(rec);t604_hide(rec);window.addEventListener('resize',t_throttle(function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(rec)}));var currentBlock=rec.querySelector('.t604');if(currentBlock){currentBlock.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(rec)})}}
function t604_show(rec){var playBtns=rec.querySelectorAll('.t604__play');Array.prototype.forEach.call(playBtns,function(play){var itemWrap=play.closest('.t604__imgwrapper');var image=itemWrap.querySelector('.t-slds__bgimg');var videoWrap=itemWrap.querySelector('.t604__wrap-video');var videoLazy=videoWrap.querySelector('.t-video-lazyload');play.addEventListener('click',function(event){event.preventDefault();event.stopPropagation();t_onFuncLoad('t_video_lazyload__addVideo',function(){videoWrap.style.display='block';image.style.opacity=0;t_video_lazyload__addVideo(videoLazy)})})})}
function t604_hide(rec){var videoWraps=rec.querySelectorAll('.t604__wrap-video');var videos=rec.querySelectorAll('.t604__wrap-video .t-video-lazyload');rec.addEventListener('updateSlider',function(){Array.prototype.forEach.call(videoWraps,function(videoWrap){videoWrap.display.style='none'});Array.prototype.forEach.call(videos,function(video){video.innerHTML=''})})}
function t604_imageHeight(rec){var images=rec.querySelectorAll('.t604__separator');Array.prototype.forEach.call(images,function(image){var imgHeight=parseInt(image.getAttribute('data-slider-image-height'));var imgWidth=parseInt(image.getAttribute('data-slider-image-width'));var imgRatio=imgHeight/imgWidth;var imgPadding=imgRatio*100;image.style.paddingBottom=imgPadding+'%'})}
function t604_arrowWidth(rec){var arrows=rec.querySelectorAll('.t-slds__arrow_wrapper');var slide=rec.querySelector('.t-slds__item_active .t-slds__wrapper');var slideWidth=slide?slide.offsetWidth:0;if(slide&&slideWidth===0){t_onFuncLoad('t_slds_SliderWidth',function(){setTimeout(function(){slideWidth=slide.offsetWidth;t604__updateArrowWidth(slideWidth,arrows)},300)})}else{t604__updateArrowWidth(slideWidth,arrows)}}
function t604__updateArrowWidth(slideWidth,arrows){var calcArrowWidth=window.innerWidth-slideWidth;var arrowWidth=window.innerWidth>960?calcArrowWidth/2+'px':'';if(arrowWidth!=='0px'&&arrowWidth!==''){Array.prototype.forEach.call(arrows,function(arrow){arrow.style.width=arrowWidth})}}
function t604__UpdateSliderArrowsHeight(recid){var sliderRec=document.getElementById('rec'+recid);if(!sliderRec)return;var activeItem=sliderRec.querySelector('.t-slds__item_active');if(activeItem){var separator=activeItem.querySelector('.t604__separator');var isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);var offsetForVideoBtns=0;var isVideo=activeItem.querySelector('[data-slider-video-type]');if(isVideo&&isMobile)offsetForVideoBtns=40;var itemPaddingTop=parseInt(getComputedStyle(activeItem).paddingTop)||0;var itemPaddingBottom=parseInt(getComputedStyle(activeItem).paddingBottom)||0;var height=itemPaddingTop+itemPaddingBottom-offsetForVideoBtns;if(separator&&separator.hasAttribute('data-slider-image-height')&&activeItem.clientHeight===0){height=parseInt(separator.getAttribute('data-slider-image-height'))-height}else{height=activeItem.clientHeight-height}}
var arrowWrappers=sliderRec.querySelectorAll('.t-slds__arrow_wrapper');if(height&&arrowWrappers.length>0){Array.prototype.forEach.call(arrowWrappers,function(arrowWrapper){arrowWrapper.style.height=height+'px';var arrow=arrowWrapper.querySelector('.t-slds__arrow');if(arrow)arrow.style.marginTop=offsetForVideoBtns/2+'px'})}}
function t190_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;rec.addEventListener('click',function(e){if(e.target.closest('.t190__button')){t190_scrollToTop()}})}
function t190_scrollToTop(){var duration=700;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=0-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');var isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);if(isSafari){t190__animateScrollPolyfill(0)}else{t190__animateScroll()}
function t190__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return(change/2)*currentTime*currentTime*currentTime+start}else{return(change/2)*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t190__animateScroll(){currentTime+=increment;window.scrollTo(0,t190__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t190__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}}
function t190__animateScrollPolyfill(target){var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(target>bottomViewportPoint)target=bottomViewportPoint;if(target===window.pageYOffset)return!1;var currentPosition=window.pageYOffset;var step=(target-currentPosition)/30;var difference=window.pageYOffset;var timerID=setInterval(function(){difference+=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if((target-currentPosition<0&&window.pageYOffset<=target)||(target-currentPosition>0&&window.pageYOffset>=target)){clearInterval(timerID);document.body.removeAttribute('data-scrollable')}},10)}
window.requestAnimationFrame=(function(){return(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60)})})();function t270_scroll(hash,offset){if(!hash)return;t270_checkLoad(hash,offset);var excludeHashes=['#!/tproduct/','#!/tab/','#opencart'];if(excludeHashes.includes(hash)){return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;t270_scrollToEl(hash,offset);if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_checkLoad(hash,offset){if(window.t270_loadChecked)return;var sliderWrappers=document.body.querySelectorAll('.t-slds__items-wrapper');if(!sliderWrappers.length)return;var lastWrapper=sliderWrappers[sliderWrappers.length-1];var sliderImgs=lastWrapper?lastWrapper.querySelectorAll('.t-slds__bgimg'):[];var lastImg=sliderImgs[sliderImgs.length-1];var imageUrl=lastImg?window.getComputedStyle(lastImg).backgroundImage:'';imageUrl=imageUrl.substring(5,imageUrl.length-2);var preloaderImg=document.createElement('img');preloaderImg.src=imageUrl?imageUrl:'';preloaderImg.addEventListener('load',function(){t270_scroll(hash,offset);window.t270_loadChecked=!0})}
function t270_scrollToEl(hash,offset){var SCROLL_DURATION_MS=500;var body=document.body;if(body.getAttribute('data-scroll'))return;var scrollTargetY=t270_getTarget(hash,offset);if(isNaN(scrollTargetY))return;var canSmoothScroll=window.CSS&&window.CSS.supports('scroll-behavior','smooth')&&'scrollBehavior' in document.documentElement.style;var userAgent=navigator.userAgent.toLowerCase();var isAndroid=userAgent.indexOf('android')!==-1;if(window.isMobile&&!isAndroid&&canSmoothScroll){body.setAttribute('data-scroll','true');window.scrollTo({left:0,top:scrollTargetY,behavior:'smooth',});setTimeout(function(){body.removeAttribute('data-scroll')},SCROLL_DURATION_MS)}else{t270_smoothScrollTo(scrollTargetY,SCROLL_DURATION_MS)}}
function t270_smoothScrollTo(targetY,duration=500){var body=document.body;var startY=window.scrollY||window.pageYOffset;var deltaY=targetY-startY;var startTime=performance.now();function easeInOutQuad(t){return Math.pow(t,2)}
function scroll(){var currentTime=performance.now();var elapsedTime=Math.min((currentTime-startTime)/duration,1);var ease=easeInOutQuad(elapsedTime);window.scrollTo(0,startY+deltaY*ease);if(elapsedTime<1){requestAnimationFrame(scroll)}else{body.removeAttribute('data-scroll');body.removeAttribute('data-scrollable');window.scrollTo(0,targetY)}}
body.setAttribute('data-scroll','true');body.setAttribute('data-scrollable','true');requestAnimationFrame(scroll)}
function t270_getTarget(hash,offset){var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"], div[id="'+hash.substr(1)+'"]');if(!target)return}
target=parseInt(target.getBoundingClientRect().top+window.pageYOffset-offset,10);target=Math.max(target,0);return target}
function t886_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var notificationBlock=rec.querySelector('.t886');var closeButton=rec.querySelector('.t886__btn');var storageItem=notificationBlock.getAttribute('data-storage-item');var lastOpen;try{lastOpen=localStorage.getItem(storageItem)}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}
if(!lastOpen){notificationBlock.classList.remove('t886_closed')}
if(closeButton){closeButton.addEventListener('click',function(event){notificationBlock.classList.add('t886_closed');try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}
event.preventDefault()})}}